kind: Service
apiVersion: v1
metadata:
  name: windows-machine-config-operator-metrics
  labels:
    name: windows-machine-config-operator
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 9182
      targetPort: 9182
