# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
    name: windows-machine-config-operator
  name: windows-machine-config-operator-metrics
spec:
  endpoints:
    - path: /metrics
      port: metrics
      interval: 30s
      honorLabels: true
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_endpoint_address_target_name
          targetLabel: instance
  selector:
    matchLabels:
      control-plane: controller-manager
      name: windows-machine-config-operator
