kind: Service
apiVersion: v1
metadata:
  name: windows-exporter
  labels:
    app.kubernetes.io/name: windows-exporter
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 9182
      targetPort: 9182

